# Generated by Django 5.0.1 on 2024-01-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zapatos',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=50)),
                ('talla', models.PositiveSmallIntegerField()),
                ('modelo', models.CharField(max_length=100)),
                ('taco', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('caracteristicas', models.TextField(blank=True)),
                ('categoria', models.CharField(max_length=100)),
                ('precio', models.PositiveIntegerField()),
                ('fecha_vendida', models.DateTimeField(blank=True, null=True)),
                ('vendido', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
